### ISSUE TITLE
select key, value pairs in variable queries

### ISSUE THREAD

**Issue by jazerda** [denniskniep/grafana-datasource-plugin-neo4j#12]
**Is your feature request related to a problem? Please describe.**
Hello , I'd like to request the ability in dashboard variable queries to rename their values to __value and __text, so that the selection may be a key / value pair.  For example ,  in a dashboard variable select box , the key be an ID and the value (text that the user) sees a NAME or DESCRIPTION of that item.

thank you
![image](https://user-images.githubusercontent.com/36823216/214336837-4ff3253f-80ae-4fee-8946-510b4c3c505e.png)

**Comment by denniskniep** [comment]
Hi,

it  already works:

Define Query Variable:
`match (n) return n.name + "__" + n.born`

with regex:
`/^(?<text>.*)__(?<value>.*)$/`

![image](https://github.com/denniskniep/grafana-datasource-plugin-neo4j/assets/3629463/246c7762-4b31-4d86-acec-dd3afb75e84c)



![image](https://github.com/denniskniep/grafana-datasource-plugin-neo4j/assets/3629463/880eb9b0-5dc6-49f6-8091-209517613376)
