### ISSUE TITLE
Neo4j queries occasionally hang

### ISSUE THREAD

**Issue by svniedner** [denniskniep/grafana-datasource-plugin-neo4j#13]
**Describe the bug**
From time to time the plugin fails to provide data, and the dashboard hangs:

t=2023-02-05T15:55:30+0000 lvl=eror msg="ConnectivityError: Can not connect to specified url." logger=plugin.initializer pluginID=kniepdennis-neo4j-datasource err="ConnectivityError: Unable to retrieve routing table from neo4j:7687: read tcp 172.19.0.4:54402->172.19.0.5:7687: i/o timeout"
t=2023-02-05T15:55:30+0000 lvl=eror msg="Error in query" logger=plugin.initializer pluginID=kniepdennis-neo4j-datasource err="ConnectivityError: Can not connect to specified url. Please review log for more details."
t=2023-02-05T15:55:30+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=400 remote_addr=192.168.178.33 time_ms=39 size=131 referer="http://192.168.178.37:3000/d/Pi5mT-A4k/new-bsi-advisories?orgId=1"
t=2023-02-05T15:55:30+0000 lvl=info msg="QueryData called" logger=plugin.initializer pluginID=kniepdennis-neo4j-datasource DATASOURCE_UID=e1ed0128-9af0-479d-be5d-d922c44acf43

This is an example from the logs, unfortunaltely I do not see more information. Grafana and Neo4j are running on the same machine, so a real network problem is highly unlikely. 

<img width="523" alt="Bildschirm­foto 2023-02-05 um 16 55 38" src="https://user-images.githubusercontent.com/92157577/216830435-baeb58cc-7c40-42e5-9c82-b69f43f6ed95.png">

**To Reproduce**
As the error only occurs from time to time (maybe one out of 50 requests) it cannot really be reproduced

**Expected behavior**
The plugin is expected to output proper data.

**Screenshots**

**Versioninfos (please complete the following information):**
 -  grafana/grafana:8.3.4 (Docker version)
 -  Neo4J 5.3.0
 - Plugins installed via environment variable, see below.
 - GF_INSTALL_PLUGINS=https://github.com/denniskniep/grafana-datasource-plugin-neo4j/releases/download/v1.1.0/kniepdennis-neo4j-datasource-1.1.0.zip;kniepdennis-neo4j-datasource,snuids-radar-panel,netsage-sankey-panel

**Additional context**
I am ready to assist in hunting down and fixing the problem.

**Comment by 985958118** [comment]
hi，have you solved this problem? I'm having the same problem and it's happening very often

**Comment by denniskniep** [comment]
Hi,
I updated the driver to newer version 5.9.0
see [Release 1.2.0 ](https://github.com/denniskniep/grafana-datasource-plugin-neo4j/releases/tag/v1.2.0)

Grafana Plugin Update in Store is already requested and its currently in review stage

But feel free to install the release manually and give feedback

**Comment by denniskniep** [comment]
Grafana Plugin 1.2.0 is released officially:
https://grafana.com/grafana/plugins/kniepdennis-neo4j-datasource

**Comment by denniskniep** [comment]
I recognized these problems also in the past. With the 1.2.0 release these errors are gone. If the errors still exists for you @985958118 @svniedner please feel free to open an issue

**Comment by svniedner** [comment]
Thanks a lot, I really appreciate and it comes precisely at the right time! I will try it out and give you feedback!
