### ISSUE TITLE
Query field not available for Grafana variables

### ISSUE THREAD

**Issue by 1n** [denniskniep/grafana-datasource-plugin-neo4j#3]
Query field is not available when using this plugin as a Data source for Grafana Query type Variables.
![image](https://user-images.githubusercontent.com/2862997/135851423-14616fc1-c6f7-4ea2-9f51-5827c8ef4646.png)

There is also an error message displayed when opening dashboard.

> Templating [BaseModule]
Error updating options: Couldn't find a query runner that matches supplied arguments.

The rest look ok, thanks for a nice plugin!

**Comment by denniskniep** [comment]
Should work now in release [v1.1.0-beta](https://github.com/denniskniep/grafana-datasource-plugin-neo4j/releases/tag/v1.1.0-beta)
(It is a complete rewrite as backend plugin with GO - therefore alerts should work also now)
