### ISSUE TITLE
Provide data for nodegraph panel

### ISSUE THREAD

**Issue by hoptical** [denniskniep/grafana-datasource-plugin-neo4j#9]
**Is your feature request related to a problem? Please describe.**
The current data source, cannot provide data frames to visualize neo4j queries via [Node graph](https://grafana.com/docs/grafana/latest/visualizations/node-graph/) panel. The node graph panel helps users to visualize graphs like what the neo4j browser does.

**Describe the solution you'd like**
The data source should be developed to handle [related data](https://grafana.com/docs/grafana/latest/visualizations/node-graph/#data-api).

**Describe alternatives you've considered**
Users can utilize [node graph API data source](https://github.com/hoptical/nodegraph-api-plugin) and develop a rest API server that handles neo4j queries. But a dedicated neo4j data source(like your repo) is absolutely a better solution.

**Additional context**
I can create a PR and develop this feature.

**Comment by denniskniep** [comment]
That would be an awesome feature!

> I can create a PR and develop this feature.

Very nice, I am happy to integrate your code changes via PR once ready

I will assign that ticket to you

**Comment by tzcole** [comment]
So glad to see this project.  I can do some testing when the PR is ready.

**Comment by hoptical** [comment]
@tzcole nice.
@denniskniep I'm busy fixing my system, and I can start developing from the following week. Is it ok?

**Comment by tzcole** [comment]
@hoptical 
Sounds good!

**Comment by feixia5712** [comment]
May I ask if this function is now available for use? Thank you
